export const SEARCH_FILMS_REQUEST = 'FILMS/SEARCH_FILMS_REQUEST';
export const SEARCH_FILMS_SUCCESS = 'FILMS/SEARCH_FILMS_SUCCESS';
export const SEARCH_FILMS_ERROR = 'FILMS/SEARCH_FILMS_ERROR';

export const CLEAR_FILM_LIST = 'FILMS/CLEAR_FILM_LIST';

export const SEARCH_AUTOCOMPLETE_FILMS_REQUEST = 'FILMS/SEARCH_AUTOCOMPLETE_FILMS_REQUEST';
export const SEARCH_AUTOCOMPLETE_FILMS_SUCCESS = 'FILMS/SEARCH_AUTOCOMPLETE_FILMS_SUCCESS';
export const SEARCH_AUTOCOMPLETE_FILMS_ERROR = 'FILMS/SEARCH_AUTOCOMPLETE_FILMS_ERROR';

export const SEARCH_FILM_REQUEST = 'FILMS/SEARCH_FILM_REQUEST';
export const SEARCH_FILM_SUCCESS = 'FILMS/SEARCH_FILM_SUCCESS';
export const SEARCH_FILM_ERROR = 'FILMS/SEARCH_FILM_ERROR';
